config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :tasks
  resources :subjects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'page#home'
  get '/calendar', to: 'calendar#show'

  resources :users do
    resources :subjects, only: [:create, :destroy]
  end

  resources :subjects do
    resources :tasks
  end

  get 'add_subject/:user_id/:subject_id', to: 'registration#add_subject'
  get 'drop_subject/:user_id/:subject_id', to: 'registration#drop_subject'

end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, :duedate, :workload, presence: true
  belongs_to :subject, optional: true

  has_many :events, dependent: :destroy
  accepts_nested_attributes_for :events, allow_destroy: true, reject_if: proc { |att| att['title'].blank? }
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_subject
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @subject.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @subject.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @subject.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to edit_subject_task_path(@subject, @task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to edit_subject_task_path(@subject, @task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to subject_tasks_path(@subject), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @subject.tasks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params
          .require(:task)
          .permit(:name, :duedate, :description, :subject_id, events_attributes: Event.attribute_names.map(&:to_sym).push(:_destroy))
    end

    def get_subject
      @subject = Subject.find(params[:subject_id])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_event_fields.html.erb
<div class="row">
  <div class="nested-fields">
    <div class="col-lg-12" style="padding: 10px;">
      <div class="card text-center" style="width: 100%;">
        <div class="card-body">
          <h5 class="card-header"><%= f.input :title %></h5>
          <p class="card-text"><%= f.input :start %></p>
          <p class="card-text"><%= f.input :end %></p>
          <p><%= f.color_field :color, value: '#00FFFF' %></p>
          <%= link_to_remove_association "remove", f, class: 'btn btn-primary btn-xs' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for([@subject, @task]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <h3>Events</h3>

  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody class='events'>
      <%= f.simple_fields_for :events do |event| %>
        <%= render 'event_fields', f: event %>
      <% end %>
    </tbody>

  </table>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', style: "margin-right: 20px;" %>
    <%= link_to_add_association 'Add Event', f, :events, class: 'btn btn-primary', data: { association_insertion_node: '.events', association_insertion_method: :append } %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Editing Task</h1>

  <%= render 'form', task: @task %>
  <br />
  <%= link_to 'Back', [@subject, @task], class: 'btn btn-primary' %>
  <br /><br /><br />
</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duedate</th>
      <th>Description</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.duedate %></td>
        <td><%= task.description %></td>
        <td><%= task.subject.name %></td>
        <td><%= link_to 'Show Subject', [@subject] %></td>
        <td><%= link_to 'Edit Task', edit_subject_task_path(@subject, task) %></td>
        <td><%= link_to 'Destroy Task', [@subject, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_subject_task_path(@subject) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', subject_tasks_path(@subject) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>Task Name:</h1>
  <%= @task.name %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @task.duedate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
<br />
<div class="btn btn-outline-primary btn-sm", style="margin-right: 20px;">
    <%= link_to 'Edit task and events', edit_subject_task_path(@subject, @task), :class => "btn text-primary" %>
  </div> 
  <div class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', subject_path(@subject), :class => "btn text-primary" %>
  </div>
  <br /><br />
<h2>Events</h2>
<div class="row">
  <% for event in Event.where(task_id: @task.id) %>
    <div class="col-lg-4 col-sm-6" style="padding: 10px;">
      <div class="card text-center" style="width: 100%;">
        <div class="card-body">
          <h5 class="card-header"><%= event.title %></h5>
          <h6 class="card-sibtitle mb-4 text-secondary">
            <%= "Start: #{event.start}" %>
          </h6>
          <p class="card-text"><%= "End: #{event.end} hrs" %></p>
          <div class="btn btn-outline-primary btn-sm">
            <%= link_to 'Show Event', event, :class => "btn text-primary" %>
          </div>
        </div>
      </div>
      </div>
  <% end %>
</div>