config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :tasks
  resources :subjects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'page#home'
  get '/calendar', to: 'calendar#show'

  resources :users do
    resources :subjects, only: [:create, :destroy]
  end

  resources :subjects do
    resources :tasks
  end

  get 'add_subject/:user_id/:subject_id', to: 'registration#add_subject'
  get 'drop_subject/:user_id/:subject_id', to: 'registration#drop_subject'

end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  belongs_to :task, optional: true

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end

end

app/controllers/events_controller.rb
# require pry;
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to do |format|
    format.html
    format.js {render layout: false}
  end

  # GET /events
  # GET /events.json
  def index
    subjectarr = Registration.where(user_id: current_user.id).to_a
    eventarr = []
    subjectarr.each do |s|
      taskarr = Subject.find_by(id: s.subject_id).tasks.to_a
      taskarr.each do |t|
        eventarr = eventarr | t.events.to_a
      end
    end
    # binding.py
    @events = Event.where(id: eventarr.map(&:id)) # Event.where(start: params[:start]..params[:end])
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.update(event_params)
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :start %>
    <%= f.input :end %>
    Label color picker:
    <%= f.color_field :color, value: '#00FFFF' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start</th>
      <th>End</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start %></td>
        <td><%= event.end %></td>
        <td><%= event.color %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Events</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<p>
  <strong>Color:</strong>
  <%= @event.color %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>