config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :tasks
  resources :subjects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'page#home'
  get '/calendar', to: 'calendar#show'

  resources :users do
    resources :subjects, only: [:create, :destroy]
  end

  resources :subjects do
    resources :tasks
  end

  get 'add_subject/:user_id/:subject_id', to: 'registration#add_subject'
  get 'drop_subject/:user_id/:subject_id', to: 'registration#drop_subject'

end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :name, :description, presence: true
  validates :name, uniqueness: true

  has_many :tasks, dependent: :destroy
  
  has_many :registrations, dependent: :destroy
  has_many :users, through: :registrations

  accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: proc { |att| att['name'].blank? }

  has_one_attached :syllabus

  def user_add=(user)
    Registration.create({ subject: Subject.find(id), user: user })
  end

  def user_drop=(user)
    if !Registration.where(user_id: user.id).find_by(subject_id: id).nil?
      Registration.where(user_id: user.id).find_by(subject_id: id).destroy
    end
  end

  def get_users
    subject = Subject.find(id)
    subject.users.to_a
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit

  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)
    @subject.owneremail = current_user.email
    if @subject.private == nil
      @subject.private = false
    end
    respond_to do |format|
      if @subject.save
        @subject.user_add = current_user
        format.html { redirect_to edit_subject_path(@subject), notice: 'Subject was successfully created.' }
        format.json { render :edit, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to edit_subject_path(@subject), notice: 'Subject was successfully updated.' }
        format.json { render :edit, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:name, :description, :syllabus,:private, tasks_attributes: Task.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= simple_form_for(@subject) do |f| %>
  <% f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  
  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-inputs">
    <%= f.file_field :syllabus %>
  </div>

  <div class="form-inputs">
      <%= f.input :private, label: 'set private' %>
  </div>

  <h3>Tasks</h3>

  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th>Task Name</th>
        <th>Due Date</th>
        <th>Workload(hr)</th>
      </tr>
    </thead>
    <tbody class='tasks'>
      <%= f.simple_fields_for :tasks do |task| %>
        <%= render 'task_fields', f: task %>
      <% end %>
    </tbody>

  </table>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', style: 'margin-right: 20px;' %>
    <%= link_to_add_association 'Add Task', f, :tasks, class: 'btn btn-primary', data: { association_insertion_node: '.tasks', association_insertion_method: :append } %>
  </div>
<% end %>

app/views/subjects/_task_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= link_to_remove_association "remove", f, class: 'btn btn-primary btn-xs' %>
  </td>
  <td>
    <% #binding.pry %> 
    <%= link_to 'Add Events', "/subjects/#{f.object.subject_id}/tasks/#{f.object.id}/edit" %>
  </td>
  <td><%= f.input :name, label: false %></td>
  <td><%= f.input :duedate, label: false %></td>
  <td><%= f.input :workload, label: false %></td>
   
</tr>

app/views/subjects/edit.html.erb
<div class="container">
  <h1>Editing Subject</h1>

  <%= render 'form', subject: @subject %>
  <br />
  <%= link_to 'Back', @subject, class: 'btn btn-primary' %>
  <br /><br /><br />
</div>

app/views/subjects/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>My Subjects</h1>
  <table class="table table-striped table-success table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>

    <tbody>
      <% @subjects.each do |subject| %>
        <% if current_user.email != subject.owneremail && !subject.private %>
          <% if !Registration.where(subject_id: subject.id).find_by(user_id: current_user.id).nil? %>
            <tr>
              <td><b><%= subject.name %></b></td>
              <td><%= subject.description.first(100) %></td>
              <td>
                <div class="btn btn-success btn-sm">
                  <%= link_to 'Show', subject, :class => "btn text-light" %>
                </div>
              </td>
              <td>
                <a href="/drop_subject/<%= current_user.id %>/<%= subject.id %>">
                    <button type="button" class="btn btn-success btn-lg">Drop</button>
                </a>
              </td>
              <td></td>
            </tr>
          <% end %>
        <% elsif current_user.email == subject.owneremail %>  
          <tr>
              <td><b><%= subject.name %></b></td>
              <td><%= subject.description.first(100) %></td>
              <td>
                <div class="btn btn-success btn-sm">
                  <%= link_to 'Show', subject, :class => "btn text-light" %>
                </div>
              </td>
              <td>
                <div class="btn btn-success btn-sm">
                  <%= link_to 'Edit', edit_subject_path(subject), :class => "btn text-light" %>
                </div>
              </td>
              <td>
                <div class="btn btn-success btn-sm">
                  <%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn text-light" %>
                </div>
              </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="btn btn-outline-dark btn-sm">
    <%= link_to 'Create New Subject', new_subject_path, :class => "btn text-dark" %>
  </div>
  <br /><br /><br />

  <h1>Other Subjects</h1>
  <table class="table table-striped table-danger table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @subjects.each do |subject| %>
        <% if current_user.email != subject.owneremail && !subject.private %>
          <% if Registration.where(subject_id: subject.id).find_by(user_id: current_user.id).nil? %>
            <tr>
              <td><b><%= subject.name %></b></td>
              <td><%= subject.description.first(30) %></td>
              <td>
                <div class="btn btn-danger btn-sm">
                  <%= link_to 'Show', subject, :class => "btn text-light" %>
                </div>
              </td>
              <td>
                <a href="/add_subject/<%= current_user.id %>/<%= subject.id %>">
                    <button type="button" class="btn btn-danger btn-lg">Add</button>
                </a>
              </td>
              <td></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <h1>Subject Name:</h1>
    <%= @subject.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @subject.description %>
  </p>
  <p>
    <strong>Syllabus:</strong>
    <% if @subject.syllabus.attached? %>
      <embed src="<%=url_for(@subject.syllabus)%>" width="600px" height="780px" />
    <% end %>
  </p>
  <br /> 
  <div class="btn btn-outline-primary btn-sm", style="margin-right: 20px;">
    <%= link_to 'Edit subject and tasks', edit_subject_path(@subject), :class => "btn text-primary" %>
  </div> 
  <div class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', subjects_path, :class => "btn text-primary" %>
  </div>
  <br /><br />
  <h2>Tasks</h2>
  <div class="row">
    <% for task in @subject.tasks %>
        <div class="col-lg-4 col-sm-6" style="padding: 10px;">
            <div class="card text-center" style="width: 100%;">
              <div class="card-body">
                <h5 class="card-header"><%= task.name %></h5>
                <h6 class="card-sibtitle mb-4 text-secondary">
                  <%= "Duedate: #{task.duedate}" %>
                </h6>
                <p class="card-text"><%= "Workload: #{task.workload} hrs" %></p>
                <div class="btn btn-outline-primary btn-sm">
                  <%= link_to 'Show Task', subject_task_path(@subject, task), :class => "btn text-primary" %>
                </div>
              </div>
            </div>
          </div>
    <% end %>
  </div>
</div>